import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {build} from 'esbuild';
import {chromium} from 'playwright';

test('preview content dragging, keyboard cycling, search and restore preserve controls',async t=>{
  const{outputFiles}=await build({bundle:true,write:false,format:'iife',platform:'browser',loader:{'.css':'text'},define:{'process.env.NODE_ENV':'"production"'},stdin:{resolveDir:process.cwd(),loader:'jsx',contents:`
    import React,{useState,useRef} from 'react';import{createRoot}from'react-dom/client';import{FloatingPreview}from'./src/client/floating-preview.jsx';import{usePreviewPanePresence,usePreviewPaneVisible}from'./src/client/preview-presence.mjs';
    window.calls=[];window.streams=[];window.EventSource=class{constructor(url){this.url=url;this.handlers={};window.streams.push(this);}addEventListener(name,fn){this.handlers[name]=fn;}close(){this.closed=true;}emit(name,value){this.handlers[name]?.({data:JSON.stringify(value)});}};
    const targets=['A','B','C'].map(id=>({kind:'tab',id,title:'Page '+id})),url=(op,id)=>'/stream?session='+id;
    function Harness(){const anchor=useRef(null),[sessionId,setSessionId]=useState('fixture'),[state,setState]=useState({enabled:true,target:targets[2],previewTargets:targets,status:'idle'}),[pane,setPane]=useState(false);window.showPane=setPane;window.switchSession=setSessionId;usePreviewPanePresence(sessionId,pane);const paneVisible=usePreviewPaneVisible(sessionId);window.stopState=()=>setState(value=>({...value,status:'stopped'}));const api=async(op,id,input)=>{window.calls.push({op,id,input});return {...state,status:'idle'};};return <div><div contentEditable suppressContentEditableWarning style={{position:'absolute',left:100,top:650,width:650,height:80}}>Input</div><div ref={anchor} style={{position:'absolute',left:100,top:750}}><FloatingPreview sessionId={sessionId} state={state} url={url} api={api} onState={setState} onError={text=>window.error=text} anchor={anchor} paneVisible={paneVisible}/></div></div>;}createRoot(document.getElementById('root')).render(<Harness/>);
  `}});
  const browser=await chromium.launch();t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1000,height:900}});page.setDefaultTimeout(3000);const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.setContent('<div id="root"></div>');await page.addStyleTag({content:await readFile(new URL(import.meta.resolve('../src/client/computer-use.css')),'utf8')});await page.addScriptTag({content:outputFiles[0].text});
  const preview=page.getByLabel('悬浮操控预览');await preview.waitFor();await page.waitForFunction(()=>window.streams.length===3);
  const settle=()=>preview.evaluate(node=>Promise.all(node.getAnimations().filter(animation=>animation.effect.getTiming().iterations!==Infinity).map(animation=>animation.finished.catch(()=>{}))));
  await settle();
  assert.equal(await preview.evaluate(node=>getComputedStyle(node).borderTopWidth),'0px');
  assert.equal(await preview.locator('.tx-cu-preview-card').first().evaluate(node=>getComputedStyle(node).borderTopWidth),'0px');
  const dragFrom=async(locator,dx,dy)=>{const box=await locator.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+dx,box.y+box.height/2+dy,{steps:8});await page.mouse.up();};
  const initial=await preview.boundingBox();
  await dragFrom(preview.getByRole('button',{name:'打开网页：Page C'}),-70,-50);
  let moved=await preview.boundingBox();assert.ok(Math.abs(moved.x-initial.x+70)<2,JSON.stringify({initial,moved}));assert.ok(Math.abs(moved.y-initial.y+50)<2);assert.deepEqual(await page.evaluate(()=>window.calls),[],'dragging the image must not open the page');
  await dragFrom(preview.locator('footer > span'),-30,-25);
  moved=await preview.boundingBox();assert.ok(Math.abs(moved.x-initial.x+100)<2);assert.ok(Math.abs(moved.y-initial.y+75)<2);
  await preview.locator('header').dblclick({position:{x:55,y:12}});
  await settle();
  const reset=await preview.boundingBox();assert.ok(Math.abs(reset.x-initial.x)<2&&Math.abs(reset.y-initial.y)<2,'double-clicking the header restores the default position');
  await dragFrom(preview.locator('footer > span'),-30,-25);
  await preview.getByRole('button',{name:'重置预览位置'}).click();
  await settle();
  const restored=await preview.boundingBox();assert.ok(Math.abs(restored.x-initial.x)<2);assert.ok(Math.abs(restored.y-initial.y)<2);
  const front=()=>preview.locator('.tx-cu-preview-card').filter({has:page.locator('.tx-cu-preview-open')}).evaluateAll(nodes=>nodes.reduce((a,b)=>Number(a.style.zIndex)>Number(b.style.zIndex)?a:b).dataset.target);
  const card=preview.getByRole('button',{name:'打开网页：Page C'});await card.focus();await card.press('ArrowRight');assert.equal(await front(),'B');await page.keyboard.press('ArrowRight');assert.equal(await front(),'A');await page.keyboard.press('ArrowRight');assert.equal(await front(),'C');
  assert.deepEqual(await page.evaluate(()=>window.calls),[]);
  await page.evaluate(()=>window.showPane(true));await preview.waitFor({state:'hidden'});
  assert.equal(await page.evaluate(()=>window.streams.every(stream=>stream.closed)),true,'the sidebar releases duplicate inline observers');
  await page.evaluate(()=>window.showPane(false));await preview.waitFor();await page.waitForFunction(()=>window.streams.length===6);await settle();
  await preview.hover();
  assert.equal(await front(),'C');assert.deepEqual(await page.evaluate(()=>window.calls),[],'pane visibility does not stop or take over the target');
  await preview.getByRole('button',{name:'展开 3',exact:true}).click();const search=preview.getByRole('searchbox',{name:'筛选预览目标'});await search.fill('Page B');assert.equal(await preview.locator('.tx-cu-preview-card:visible').count(),1);assert.equal(await page.evaluate(()=>window.streams.length),6,'filtering does not reconnect preview streams');
  await search.fill('missing');await preview.getByText('没有匹配的窗口或网页').waitFor();await search.press('Escape');assert.equal(await search.inputValue(),'');await search.press('Escape');await search.waitFor({state:'hidden'});
  await page.evaluate(()=>window.stopState());await preview.hover();await preview.getByRole('button',{name:'从预览恢复助手'}).click();assert.deepEqual(await page.evaluate(()=>window.calls.map(call=>call.op)),['resume']);
  const interrupted=await preview.getByRole('button',{name:'打开网页：Page C'}).boundingBox();
  await page.mouse.move(interrupted.x+interrupted.width/2,interrupted.y+interrupted.height/2);await page.mouse.down();await page.mouse.move(interrupted.x+interrupted.width/2-40,interrupted.y+interrupted.height/2-30,{steps:4});
  await page.evaluate(()=>window.switchSession('next-session'));await page.waitForFunction(()=>window.streams.some(stream=>stream.url.includes('next-session')));await page.mouse.up();await preview.waitFor();await settle();
  const switched=await preview.boundingBox();assert.ok(Math.abs(switched.x-initial.x)<2&&Math.abs(switched.y-initial.y)<2,JSON.stringify({message:'switching sessions cancels an active drag and restores placement',initial,switched}));assert.equal(await preview.evaluate(node=>node.classList.contains('is-dragging')),false);assert.deepEqual(errors,[]);
  await preview.getByRole('button',{name:'关闭操控预览'}).focus();await page.keyboard.press('Escape');await preview.waitFor({state:'hidden'});assert.equal(await page.getByRole('button',{name:'悬浮预览',exact:true}).getAttribute('aria-expanded'),'false');assert.equal(await page.evaluate(()=>window.error??''),'');
  await page.evaluate(()=>window.showPane(true));await page.evaluate(()=>window.showPane(false));assert.equal(await preview.count(),0,'a manually closed preview stays closed');
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.getByRole('button',{name:'悬浮预览',exact:true}).click();await preview.getByRole('button',{name:'打开网页：Page C'}).click();await preview.waitFor({state:'hidden'});assert.deepEqual(await page.evaluate(()=>window.calls.map(call=>call.op)),['resume','view-tab'],'a normal image click still opens the page');
});
